export const testData =  [
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'Yes',
        homeBuyingJourney: "I'm just researching",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '50000',
        additionalIncome: 'No',
        dependents: '0',
        anycreditcardbalance: '0',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '0',
        expectedQuote: 'You could borrow up to £237,500 over a term of 25 years.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'No',
        homeBuyingJourney: "I'm viewing properties",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '100000',
        additionalIncome: 'No',
        dependents: '1',
        anycreditcardbalance: '0',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '0',
        expectedQuote: 'You could borrow up to £475,000 over a term of 25 years.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'Yes',
        homeBuyingJourney: "I'm ready to make an offer",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '60000',
        additionalIncome: 'No',
        dependents: '2',
        anycreditcardbalance: '0',
        anyloanspaybackmonthly: '4000',
        anyothermonthlyexpense: '0',
        expectedQuote: 'We don’t think we can lend to you right now.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'No',
        homeBuyingJourney: "I've had an offer accepted",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '45000',
        additionalIncome: 'No',
        dependents: '3 or more',
        anycreditcardbalance: '2000',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '800',
        expectedQuote: 'You could borrow up to £95,880 over a term of 25 years.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'Yes',
        homeBuyingJourney: "I'm viewing properties",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '40000',
        additionalIncome: 'No',
        dependents: '0',
        anycreditcardbalance: '0',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '500',
        expectedQuote: 'You could borrow up to £141,495 over a term of 25 years.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'No',
        homeBuyingJourney: "I'm just researching",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '70000',
        additionalIncome: 'No',
        dependents: '3 or more',
        anycreditcardbalance: '0',
        anyloanspaybackmonthly: '3000',
        anyothermonthlyexpense: '1000',
        expectedQuote: 'We don’t think we can lend to you right now.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'Yes',
        homeBuyingJourney: "I'm ready to make an offer",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '30000',
        additionalIncome: 'No',
        dependents: '2',
        anycreditcardbalance: '2000',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '700',
        expectedQuote: 'We don’t think we can lend to you right now.'
    },
    {
        whatToDo: 'I want to buy a home',
        firstHome: 'No',
        homeBuyingJourney: "I've had an offer accepted",
        peopleApplying: 'Just me',
        whatToKnow: 'How much could I borrow?',
        employmentStatus: 'Employed',
        salary: '25000',
        additionalIncome: 'No',
        dependents: '3 or more',
        anycreditcardbalance: '500',
        anyloanspaybackmonthly: '0',
        anyothermonthlyexpense: '300',
        expectedQuote: 'You could borrow up to £27,940 over a term of 25 years.'
    }
]